  INSERT INTO `permissions` VALUES (`cmd_bubblealert` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_rolldice` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_closedice` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_closedice_room` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
   INSERT INTO `permissions` VALUES ( `cmd_makecasino` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_yeet` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_stats` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_dance` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
   INSERT INTO `permissions` VALUES ( `cmd_online` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
    INSERT INTO `permissions` VALUES (`cmd_buildheight` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
   INSERT INTO `permissions` VALUES ( `cmd_welcome` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_brb` enum('0','1','2') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
   INSERT INTO `permissions` VALUES ( `cmd_pay` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '1');
   INSERT INTO `permissions` VALUES ( `cmd_freezeroom` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_givecommand` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_remcommand` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_eggify` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_poof` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_kiss` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_tea` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_hug` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_kill` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
   INSERT INTO `permissions` VALUES ( `cmd_nuke` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
    INSERT INTO `permissions` VALUES (`cmd_slime` enum('0','1') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0');
